runtime: nodejs22
service: studyarena-backend
instance_class: F2
entrypoint: node dist/main.js

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  DATABASE_URL: "postgresql://tsuser:tsuser1234@localhost:5432/geobukschool_prod?host=/cloudsql/ts-back-nest-479305:asia-northeast3:geobuk-db&schema=studyarena,hub,jungsi"
  AUTH_SECRET: "AIetry5Dr+7rPJBj01hYdoKT0gxBk28JD8PPJVEQSa4MBnPGMAwH7tkSUx0BLaBRSysleQlcuSXLLeox0nVhTg=="
  HUB_API_URL: "https://ts-back-nest-479305.du.r.appspot.com"
  SERVICE_ID: "studyarena"
  CORS_ORIGIN: "https://studyarena-front-479305.web.app"

beta_settings:
  cloud_sql_instances: "ts-back-nest-479305:asia-northeast3:geobuk-db"

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

handlers:
  - url: /.*
    script: auto
    secure: always
